// <auto-generated />
namespace GameShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_News_and_NewsFeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_News_and_NewsFeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201612140430083_add_News_and_NewsFeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
